<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-28 at 10:11:18.
 */
class AppCtrlTest extends PHPUnit_Framework_TestCase {

    /**
     * @var AppCtrl
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new AppCtrl;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers AppCtrl::fatalError
     * @todo   Implement testFatalError().
     */
    public function testFatalError() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppCtrl::normalError
     * @todo   Implement testNormalError().
     */
    public function testNormalError() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AppCtrl::log
     * @todo   Implement testLog().
     */
    public function testLog() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
